version: '3.9'
services:
  client:
    build: ./client
    ports:
      - '3001:3000'
    working_dir: /client
  
  backend:
    build: ./backend
    ports:
    - '5001:5000'
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 2717:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongodb-data:/data/db

    
volumes:
  mongodb-data: {}