version: '3.9'
services:

  #Our mongo database service
  mongo:

    #Using the latest mongo image
    image: mongo
    #Restart in case of any failures
    restart: always
    ports:
      - "27027:27027"
    
    #Where mongo data will be stored on the local machine
    volumes:
      - mongodb-data:/data/db
    
    #Mongo atlas database credentials
    environment:
      MONGO_INITDB_ROOT_USERNAME: matangi
      MONGO_INITDB_ROOT_PASSWORD: matangi
  
  #The backend servive
  backend:
    build: ./backend
    ports:
    - "5000:5000"
    depends_on:
      - mongo
  
  #The frontend service
  client:
    build: ./client
    ports:
      - "3000:3000"

    #allow interactive mode
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodb-data: {}