apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-backend
    
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: backendcontainer
          image: mertangy/yolo-backend:v1
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: yolo-pv
            mountPath: /var/www/html
      volumes:
      - name: yolo-pv
        persistentVolumeClaim:
          claimName: yolo-pvc        
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-back
  labels:
    app: yolo-backend
spec:
  selector:
    app: yolo-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http     