apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-api
    
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo-api
    spec:
      containers:
        - name: yolo-api
          image: mertangy/yolo-backend:v1.0.0
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: yolo-pv
            mountPath: /var/www/html
      volumes:
      - name: yolo-pv
        persistentVolumeClaim:
          claimName: yolo-pvc        
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
spec:
  selector:
    app: yolo-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http     